settings:
  mob-spawns: true
  fast-crystal: true
  tp-requests: true
  notifications: true
  chat-messages: true
  combat-alerts: true
  server-announcements: true

tpa:
  request-timeout-seconds: 30
  teleport-delay-seconds: 5
  cancel-on-move: true
  cancel-on-damage: true

auction:
  expire-days: 7
  max-price: 1000000000
