package net.sunlightsmp.playersettings;
import net.milkbowl.vault.economy.Economy;import org.bukkit.*;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.entity.Player;import java.io.*;import java.util.*;
public final class BountyManager{private final SunlightPlayerSettings p;private final File f;private final Map<UUID,T> a=new LinkedHashMap<>();private final List<R> history=new ArrayList<>();
public BountyManager(SunlightPlayerSettings p){this.p=p;f=new File(p.getDataFolder(),"bounties.yml");load();}private Economy e(){var r=p.getServer().getServicesManager().getRegistration(Economy.class);return r==null?null:r.getProvider();}
public synchronized void load(){a.clear();history.clear();if(!f.exists())return;YamlConfiguration y=YamlConfiguration.loadConfiguration(f);var s=y.getConfigurationSection("active");if(s!=null)for(String k:s.getKeys(false))try{UUID id=UUID.fromString(k);T t=new T(id,s.getString(k+".name","Unknown"));var c=s.getConfigurationSection(k+".c");if(c!=null)for(String u:c.getKeys(false)){UUID q=UUID.fromString(u);t.c.put(q,new C(q,c.getString(u+".name","Unknown"),c.getDouble(u+".amount")));}if(t.total()>0)a.put(id,t);}catch(Exception ignored){}}
public synchronized void save(){YamlConfiguration y=new YamlConfiguration();for(T t:a.values()){String x="active."+t.id;y.set(x+".name",t.name);for(C c:t.c.values()){String q=x+".c."+c.id;y.set(q+".name",c.name);y.set(q+".amount",c.amount);}}List<Map<String,Object>> hs=new ArrayList<>();for(R r:history){Map<String,Object> z=new LinkedHashMap<>();z.put("target",r.target.toString());z.put("target-name",r.targetName);z.put("killer",r.killer.toString());z.put("killer-name",r.killerName);z.put("reward",r.reward);z.put("time",r.time);hs.add(z);}y.set("history",hs);try{y.save(f);}catch(IOException ex){p.getLogger().warning("bounties.yml: "+ex.getMessage());}}
public synchronized T get(UUID u){return a.get(u);}public synchronized List<R> history(){return new ArrayList<>(history);}public synchronized List<T> active(){return a.values().stream().sorted(Comparator.comparingDouble(T::total).reversed()).toList();}
public synchronized boolean place(Player from,Player target,double n){Economy e=e();double min=p.getConfig().getDouble("bounty.minimum",1000),max=p.getConfig().getDouble("bounty.maximum",10000000);if(e==null||target==null||target.equals(from)||!Double.isFinite(n)||n<min||n>max||!e.has(from,n))return false;T t=a.computeIfAbsent(target.getUniqueId(),u->new T(u,target.getName()));if(t.total()+n>max||!e.withdrawPlayer(from,n).transactionSuccess())return false;C old=t.c.get(from.getUniqueId());t.c.put(from.getUniqueId(),new C(from.getUniqueId(),from.getName(),n+(old==null?0:old.amount)));save();target.sendMessage(ChatColor.RED+"⚠ BOUNTY PLACED! $"+money(n)+" added. Total: $"+money(t.total()));if(n>=p.getConfig().getDouble("bounty.announcement-threshold",500000))Bukkit.broadcastMessage(ChatColor.RED+"🔥 BOUNTY ALERT "+ChatColor.WHITE+"$"+money(t.total())+" bounty on "+target.getName()+"!");return true;}
public synchronized boolean cancel(Player from,UUID target){if(!p.getConfig().getBoolean("bounty.allow-cancel",true))return false;T t=a.get(target);if(t==null)return false;C c=t.c.remove(from.getUniqueId());if(c==null)return false;if(p.getConfig().getBoolean("bounty.refund-on-cancel",true)){Economy e=e();if(e!=null)e.depositPlayer(Bukkit.getOfflinePlayer(c.id),c.amount);}if(t.c.isEmpty())a.remove(target);save();return true;}
public synchronized boolean claim(Player killer,Player target){if(killer==null||target==null||killer.equals(target))return false;T t=a.remove(target.getUniqueId());if(t==null)return false;Economy e=e();double reward=t.total();if(e==null||!e.depositPlayer(killer,reward).transactionSuccess()){a.put(target.getUniqueId(),t);return false;}history.add(new R(target.getUniqueId(),target.getName(),killer.getUniqueId(),killer.getName(),reward,System.currentTimeMillis()));save();killer.sendMessage(ChatColor.GREEN+"🎯 BOUNTY CLAIMED! You received $"+money(reward));target.sendMessage(ChatColor.RED+"💀 Your $"+money(reward)+" bounty was claimed by "+killer.getName()+".");for(C c:t.c.values()){Player q=Bukkit.getPlayer(c.id);if(q!=null)q.sendMessage(ChatColor.YELLOW+"🎯 Your bounty on "+target.getName()+" was claimed! Killer: "+killer.getName()+" • $"+money(c.amount));}return true;}
public synchronized boolean remove(UUID target){T t=a.remove(target);if(t==null)return false;Economy e=e();if(e!=null)for(C c:t.c.values())e.depositPlayer(Bukkit.getOfflinePlayer(c.id),c.amount);save();return true;}public synchronized boolean add(Player target,double n){double max=p.getConfig().getDouble("bounty.maximum",10000000);if(target==null||n<=0||n>max)return false;T t=a.computeIfAbsent(target.getUniqueId(),u->new T(u,target.getName()));if(t.total()+n>max)return false;UUID id=UUID.randomUUID();t.c.put(id,new C(id,"ADMIN",n));save();return true;}public synchronized boolean clear(){if(a.isEmpty())return false;for(T t:a.values())for(C c:t.c.values()){Economy e=e();if(e!=null)e.depositPlayer(Bukkit.getOfflinePlayer(c.id),c.amount);}a.clear();save();return true;}public String money(double n){return String.format(Locale.US,"%.2f",n);}
public record R(UUID target,String targetName,UUID killer,String killerName,double reward,long time){} public static final class T{final UUID id;final String name;final Map<UUID,C> c=new LinkedHashMap<>();T(UUID i,String n){id=i;name=n;}public double total(){return c.values().stream().mapToDouble(x->x.amount).sum();}}public record C(UUID id,String name,double amount){}}
