package net.sunlightsmp.playersettings;
import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.entity.PlayerDeathEvent;import org.bukkit.event.inventory.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import java.util.*;
public final class BountyCommand implements CommandExecutor,Listener{final SunlightPlayerSettings p;final BountyManager m;final Map<UUID,UUID> cancel=new HashMap<>();final Map<String,Long> farm=new HashMap<>();static final String MAIN="☀ Bounty",LIST="☀ Active Bounties",MINE="☀ My Bounties",HIST="☀ Bounty History",CONF="☀ Confirm Bounty Cancel";public BountyCommand(SunlightPlayerSettings p,BountyManager m){this.p=p;this.m=m;}
ItemStack i(Material z,String n,String...l){ItemStack x=new ItemStack(z);ItemMeta q=x.getItemMeta();q.setDisplayName(n);q.setLore(Arrays.asList(l));x.setItemMeta(q);return x;}void f(Inventory x){for(int s=0;s<x.getSize();s++)x.setItem(s,i(Material.BLACK_STAINED_GLASS_PANE," "));}
void main(Player x){Inventory i=p.getServer().createInventory(null,54,MAIN);f(i);i.setItem(20,i(Material.TARGET,"🎯 Place Bounty","/bounty <player> <amount>"));i.setItem(22,i(Material.COMPASS,"🔎 Browse Bounties"));i.setItem(24,i(Material.PAPER,"📋 My Bounties"));i.setItem(30,i(Material.WRITABLE_BOOK,"🏆 Bounty History"));i.setItem(32,i(Material.NETHER_STAR,"🔥 Top Bounties"));x.openInventory(i);}
void list(Player x){Inventory i=p.getServer().createInventory(null,54,LIST);f(i);int s=10;for(BountyManager.T b:m.active()){if(s>=44)break;i.setItem(s,i(Material.PLAYER_HEAD,"🔴 "+b.name,"💰 $"+m.money(b.total()),"👥 "+b.c.size(),"Click for details"));s++;if(s%9==8)s+=2;}i.setItem(49,i(Material.ARROW,"Back"));x.openInventory(i);}
void mine(Player x){Inventory i=p.getServer().createInventory(null,54,MINE);f(i);int s=10;for(BountyManager.T b:m.active())if(b.c.containsKey(x.getUniqueId())){var c=b.c.get(x.getUniqueId());i.setItem(s,i(Material.REDSTONE,b.name,"Your: $"+m.money(c.amount()),"Total: $"+m.money(b.total()),"Click to cancel"));s++;if(s%9==8)s+=2;}i.setItem(49,i(Material.ARROW,"Back"));x.openInventory(i);}
void hist(Player x){Inventory i=p.getServer().createInventory(null,54,HIST);f(i);int s=10;for(BountyManager.R r:m.history()){if(s>=44)break;i.setItem(s,i(Material.PAPER,"🎯 "+r.targetName(),"💰 $"+m.money(r.reward()),"⚔ Claimed by: "+r.killerName(),new Date(r.time()).toString()));s++;if(s%9==8)s+=2;}if(s==10)i.setItem(22,i(Material.BARRIER,"No bounty history yet"));i.setItem(49,i(Material.ARROW,"Back"));x.openInventory(i);}
public boolean onCommand(org.bukkit.command.CommandSender s,org.bukkit.command.Command c,String l,String[] a){if(!(s instanceof Player x))return true;if(a.length==0){main(x);return true;}if(a[0].equalsIgnoreCase("list")){list(x);return true;}if(a[0].equalsIgnoreCase("history")){hist(x);return true;}if(a[0].equalsIgnoreCase("cancel")&&a.length>1){Player t=Bukkit.getPlayerExact(a[1]);if(t!=null&&m.cancel(x,t.getUniqueId()))x.sendMessage("☀ Bounty cancelled and refunded.");else x.sendMessage("☀ No cancellable bounty found.");return true;}if(a.length>1){Player t=Bukkit.getPlayerExact(a[0]);double n;try{n=Double.parseDouble(a[1]);}catch(Exception e){x.sendMessage("☀ Invalid amount.");return true;}if(t==null){x.sendMessage("☀ Player must be online.");return true;}if(m.place(x,t,n))x.sendMessage("☀ Bounty placed! Target: "+t.getName()+" Reward: $"+m.money(n));else x.sendMessage("☀ Could not place bounty. Check balance and limits.");return true;}x.sendMessage("/bounty <player> <amount> | list | history | cancel <player>");return true;}
@EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player x))return;String t=e.getView().getTitle();if(!Set.of(MAIN,LIST,MINE,HIST,CONF).contains(t))return;e.setCancelled(true);if(t.equals(MAIN)){if(e.getRawSlot()==22)list(x);else if(e.getRawSlot()==24)mine(x);else if(e.getRawSlot()==30)hist(x);else if(e.getRawSlot()==32)list(x);return;}if(e.getRawSlot()==49){main(x);return;}if(t.equals(MINE)){ItemStack z=e.getCurrentItem();if(z!=null){String n=ChatColor.stripColor(z.getItemMeta().getDisplayName());Player q=Bukkit.getPlayerExact(n);if(q!=null){cancel.put(x.getUniqueId(),q.getUniqueId());Inventory v=p.getServer().createInventory(null,27,CONF);f(v);v.setItem(11,i(Material.LIME_WOOL,"CONFIRM"));v.setItem(15,i(Material.RED_WOOL,"CANCEL"));x.openInventory(v);}}return;}if(t.equals(CONF)){if(e.getRawSlot()==11){UUID u=cancel.remove(x.getUniqueId());if(u!=null)m.cancel(x,u);mine(x);}else if(e.getRawSlot()==15){cancel.remove(x.getUniqueId());mine(x);}}}
@EventHandler public void death(PlayerDeathEvent e){Player t=e.getEntity(),k=t.getKiller();if(k==null||k.equals(t)||m.get(t.getUniqueId())==null)return;if(p.getConfig().getBoolean("bounty.require-pvp",true)&&(!p.isPlayerInCombat(t)||!p.isPlayerInCombat(k)))return;if(!p.hasPermission("bounty.bypass")&&p.getTeamManager()!=null&&p.getTeamManager().getTeam(t.getUniqueId())!=null&&p.getTeamManager().getTeam(t.getUniqueId())==p.getTeamManager().getTeam(k.getUniqueId())&&p.getConfig().getBoolean("bounty.block-team-kills",true))return;String key=t.getUniqueId()+"|"+k.getUniqueId();long now=System.currentTimeMillis(),cd=p.getConfig().getLong("bounty.kill-cooldown-minutes",30)*60000;Long last=farm.get(key);if(last!=null&&now-last<cd){k.sendMessage("☀ Bounty claim blocked by anti-farming protection.");return;}farm.put(key,now);m.claim(k,t);}}
