package net.sunlightsmp.playersettings;
import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.inventory.*;import org.bukkit.event.player.AsyncPlayerChatEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import java.util.*;
public final class OrderCommand implements CommandExecutor,Listener{
 private final SunlightPlayerSettings p;private final OrderManager m;private final Map<UUID,W> w=new HashMap<>();private final Map<UUID,Long> f=new HashMap<>();private static final String MAIN="☀ Player Orders";
 public OrderCommand(SunlightPlayerSettings p,OrderManager m){this.p=p;this.m=m;}
 private ItemStack it(Material x,String n,String...l){ItemStack i=new ItemStack(x);ItemMeta z=i.getItemMeta();z.setDisplayName(n);z.setLore(Arrays.asList(l));i.setItemMeta(z);return i;}
 private void fill(Inventory i){for(int n=0;n<i.getSize();n++)i.setItem(n,it(Material.BLACK_STAINED_GLASS_PANE," "));for(int n:new int[]{0,1,2,3,4,5,6,7,8,45,46,47,48,50,51,52,53})i.setItem(n,it(Material.YELLOW_STAINED_GLASS_PANE,ChatColor.GOLD+"☀"));}
 private String nice(Material x){String s=x.name().toLowerCase(Locale.ROOT).replace('_',' ');return Character.toUpperCase(s.charAt(0))+s.substring(1);}
 private String left(long e){long s=Math.max(0,e-System.currentTimeMillis())/1000,d=s/86400,h=s%86400/3600,mi=s%3600/60;return d>0?d+"d "+h+"h":h>0?h+"h "+mi+"m":mi+"m";}
 private long dur(String s){try{s=s.toLowerCase();long x=s.endsWith("h")?3600000L:s.endsWith("d")?86400000L:0,n=Long.parseLong(s.substring(0,s.length()-1));long max=p.getConfig().getLong("order.max-expiration-days",7)*86400000L;return x>0?Math.min(n*x,max):-1;}catch(Exception e){return -1;}}
 public boolean onCommand(org.bukkit.command.CommandSender s,org.bukkit.command.Command c,String l,String[]a){if(!(s instanceof Player q))return true;if(a.length==0){main(q);return true;}switch(a[0].toLowerCase()){case"create":if(a.length<4){q.sendMessage(ChatColor.YELLOW+"☀ /order create <item> <amount> <total-price> [1h|6h|1d|3d|7d]");return true;}Material x=Material.matchMaterial(a[1]);try{int n=Integer.parseInt(a[2]);double price=Double.parseDouble(a[3]);long d=dur(a.length>4?a[4]:"7d");if(x==null||x.isAir()||n<=0||price<=0||d<=0)throw new Exception();Order o=m.create(q,new ItemStack(x),n,price,System.currentTimeMillis()+d);q.sendMessage(o==null?ChatColor.RED+"☀ Order could not be created. Check balance/limits/items.":ChatColor.GREEN+"☀ Order #"+o.id()+" created.");}catch(Exception e){q.sendMessage(ChatColor.RED+"☀ Invalid order.");}return true;case"search":if(a.length<2){q.sendMessage(ChatColor.YELLOW+"☀ /order search <item>");return true;}browse(q,m.search(a[1]));return true;case"cancel":try{long id=Long.parseLong(a[1]);q.sendMessage(m.cancel(q,id)?ChatColor.GREEN+"☀ Order cancelled and escrow refunded.":ChatColor.RED+"☀ You can only cancel your own active order.");}catch(Exception e){q.sendMessage(ChatColor.RED+"☀ Invalid order ID.");}return true;case"myorders":my(q);return true;case"history":hist(q);return true;default:main(q);return true;}}
 private void main(Player q){Inventory i=p.getServer().createInventory(null,54,MAIN);fill(i);i.setItem(20,it(Material.EMERALD,ChatColor.GREEN+"🛒 Create Order","Use /order create <item> <amount> <price> [expiry]"));i.setItem(22,it(Material.CHEST,ChatColor.YELLOW+"📦 My Orders","Active orders and statuses"));i.setItem(24,it(Material.COMPASS,ChatColor.AQUA+"🔎 Browse Orders","Public player orders"));i.setItem(31,it(Material.WRITABLE_BOOK,ChatColor.GOLD+"📋 My Order History","Completed, expired and cancelled"));q.openInventory(i);}
 private void browse(Player q,List<Order> os){Inventory i=p.getServer().createInventory(null,54,ChatColor.DARK_AQUA+"☀ Browse Orders");fill(i);int slot=10;for(Order o:os){if(slot>=44)break;i.setItem(slot,it(o.item().getType(),ChatColor.AQUA+"#"+o.id()+" "+nice(o.item().getType()),ChatColor.GRAY+"📦 "+o.remaining()+" needed",ChatColor.GREEN+"💰 $"+m.money(o.totalPrice()),ChatColor.YELLOW+"💵 $"+m.money(o.pricePerItem())+" / item",ChatColor.GRAY+"👤 "+o.buyerName(),ChatColor.GRAY+"⏰ "+left(o.expiresAt()),ChatColor.DARK_GRAY+"Click to view"));slot++;if(slot%9==8)slot+=2;}q.openInventory(i);}
 private void detail(Player q,Order o){Inventory i=p.getServer().createInventory(null,27,ChatColor.AQUA+"☀ Order #"+o.id());fill(i);i.setItem(4,o.item().clone());i.setItem(11,it(Material.PAPER,ChatColor.WHITE+"Details","Item: "+nice(o.item().getType()),"Remaining: "+o.remaining(),"Reward: $"+m.money(o.totalPrice()),"Per item: $"+m.money(o.pricePerItem()),"Ordered by: "+o.buyerName(),"Expires: "+left(o.expiresAt())));i.setItem(15,it(Material.HOPPER,ChatColor.GREEN+"FULFILL ORDER","Put items in the confirmation screen"));q.openInventory(i);}
 private void fulfill(Player q,Order o){f.put(q.getUniqueId(),o.id());Inventory i=p.getServer().createInventory(null,27,ChatColor.GREEN+"☀ Fulfill #"+o.id());fill(i);i.setItem(4,o.item().clone());i.setItem(13,it(o.item().getType(),ChatColor.WHITE+"PUT ITEMS HERE","Place requested items here","Maximum: "+o.remaining()));i.setItem(15,it(Material.LIME_WOOL,ChatColor.GREEN+"CONFIRM","Payment + delivery happen atomically"));i.setItem(22,it(Material.BARRIER,ChatColor.RED+"CANCEL"));q.openInventory(i);}
 private void my(Player q){Inventory i=p.getServer().createInventory(null,54,ChatColor.YELLOW+"☀ My Orders");fill(i);int s=10;for(Order o:m.byBuyer(q.getUniqueId(),true)){if(s>=44)break;i.setItem(s,it(o.item().getType(),ChatColor.YELLOW+"#"+o.id()+" "+nice(o.item().getType()),"Remaining: "+o.remaining(),"Status: "+o.status(),o.status().equals("ACTIVE")?"Click to cancel":""));s++;if(s%9==8)s+=2;}q.openInventory(i);}
 private void hist(Player q){Inventory i=p.getServer().createInventory(null,54,ChatColor.GOLD+"☀ Order History");fill(i);int s=10;for(Order o:m.byBuyer(q.getUniqueId(),false)){if(s>=44)break;i.setItem(s,it(o.item().getType(),ChatColor.GOLD+"#"+o.id()+" "+nice(o.item().getType()),"Status: "+o.status(),"Original total: $"+m.money(o.totalPrice())));s++;if(s%9==8)s+=2;}q.openInventory(i);}
 @EventHandler public void chat(AsyncPlayerChatEvent e){W z=w.get(e.getPlayer().getUniqueId());if(z==null)return;e.setCancelled(true);try{if(z.step==1){z.amount=Integer.parseInt(e.getMessage());if(z.amount<=0)throw new Exception();z.step=2;e.getPlayer().sendMessage(ChatColor.YELLOW+"☀ Enter total price:");}else if(z.step==2){z.price=Double.parseDouble(e.getMessage());if(z.price<=0)throw new Exception();z.step=3;e.getPlayer().sendMessage(ChatColor.YELLOW+"☀ Enter expiration: 1h, 6h, 1d, 3d or 7d");}else{long d=dur(e.getMessage());if(d<=0)throw new Exception();w.remove(e.getPlayer().getUniqueId());Order o=m.create(e.getPlayer(),z.item,z.amount,z.price,System.currentTimeMillis()+d);e.getPlayer().sendMessage(o==null?ChatColor.RED+"☀ Order could not be created.":ChatColor.GREEN+"☀ Order #"+o.id()+" created.");}}catch(Exception x){e.getPlayer().sendMessage(ChatColor.RED+"☀ Invalid value, try again.");}}
 @EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player q))return;String t=e.getView().getTitle();if(t.equals(MAIN)){e.setCancelled(true);if(e.getRawSlot()==20){q.closeInventory();ItemStack hand=q.getInventory().getItemInMainHand();if(hand.getType().isAir()){q.sendMessage(ChatColor.RED+"☀ Hold the item you want to order in your main hand.");return;}w.put(q.getUniqueId(),new W(hand.clone()));q.sendMessage(ChatColor.YELLOW+"☀ Enter amount in chat:");}else if(e.getRawSlot()==22)my(q);else if(e.getRawSlot()==24)browse(q,m.active());else if(e.getRawSlot()==31)hist(q);}else if(t.startsWith(ChatColor.DARK_AQUA+"☀ Browse Orders")){e.setCancelled(true);ItemStack x=e.getCurrentItem();if(x!=null&&x.hasItemMeta()&&x.getItemMeta().getDisplayName().startsWith(ChatColor.AQUA+"#"))try{long id=Long.parseLong(x.getItemMeta().getDisplayName().replaceAll("\D+",""));Order o=m.get(id);if(o!=null)detail(q,o);}catch(Exception ignored){}}else if(t.startsWith(ChatColor.AQUA+"☀ Order #")){e.setCancelled(true);if(e.getRawSlot()==15)try{long id=Long.parseLong(t.replaceAll("\D+",""));Order o=m.get(id);if(o!=null)fulfill(q,o);}catch(Exception ignored){}}else if(t.startsWith(ChatColor.GREEN+"☀ Fulfill #")){if(e.getRawSlot()!=13)e.setCancelled(true);if(e.getRawSlot()==15){e.setCancelled(true);Long id=f.get(q.getUniqueId());Order o=id==null?null:m.get(id);ItemStack x=e.getView().getTopInventory().getItem(13);if(o==null||x==null||x.getType().isAir()||!x.isSimilar(o.item())){q.sendMessage(ChatColor.RED+"☀ Put the exact requested item in the slot.");return;}int n=Math.min(x.getAmount(),o.remaining());ItemStack give=x.clone();give.setAmount(n);if(m.fulfill(q,id,give)){e.getView().getTopInventory().setItem(13,null);f.remove(q.getUniqueId());q.closeInventory();}else q.sendMessage(ChatColor.RED+"☀ Fulfillment failed safely. Nothing was taken.");}else if(e.getRawSlot()==22){f.remove(q.getUniqueId());q.closeInventory();}}else if(t.startsWith(ChatColor.YELLOW+"☀ My Orders")){e.setCancelled(true);ItemStack x=e.getCurrentItem();if(x!=null&&x.hasItemMeta()&&x.getItemMeta().getDisplayName().startsWith(ChatColor.YELLOW+"#"))try{long id=Long.parseLong(x.getItemMeta().getDisplayName().replaceAll("\D+",""));if(m.cancel(q,id))my(q);}catch(Exception ignored){}}else if(t.startsWith(ChatColor.GOLD+"☀ Order History"))e.setCancelled(true);}
 private static final class W{final ItemStack item;int step=1,amount;double price;W(ItemStack i){item=i;}}
}