package net.sunlightsmp.playersettings;
import net.milkbowl.vault.economy.Economy;import org.bukkit.*;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.entity.Player;import org.bukkit.inventory.ItemStack;import java.io.*;import java.util.*;
public final class OrderManager{
 private final SunlightPlayerSettings p;private final File f;private YamlConfiguration d;private final Map<Long,Order>a=new LinkedHashMap<>(),h=new LinkedHashMap<>();private long next=1;
 public OrderManager(SunlightPlayerSettings p){this.p=p;f=new File(p.getDataFolder(),"orders.yml");load();p.getServer().getScheduler().runTaskTimer(p,this::expire,20L,600L);}
 private Economy eco(){var r=p.getServer().getServicesManager().getRegistration(Economy.class);return r==null?null:r.getProvider();}
 public synchronized void load(){try{p.getDataFolder().mkdirs();if(!f.exists())f.createNewFile();}catch(IOException ignored){}d=YamlConfiguration.loadConfiguration(f);next=d.getLong("next-id",1);a.clear();h.clear();read("active",a);read("history",h);expire();}
 private void read(String s,Map<Long,Order>m){var q=d.getConfigurationSection(s);if(q==null)return;for(String k:q.getKeys(false))try{var c=d.getConfigurationSection(s+"."+k);ItemStack i=c.getItemStack("item");if(i!=null)m.put(Long.parseLong(k),new Order(Long.parseLong(k),UUID.fromString(c.getString("buyer")),c.getString("buyer-name","Unknown"),i,c.getInt("remaining"),c.getDouble("total"),c.getDouble("per"),c.getLong("expires"),c.getString("status","UNKNOWN")));}catch(Exception ignored){}}
 public synchronized void save(){d=new YamlConfiguration();d.set("next-id",next);write("active",a);write("history",h);try{d.save(f);}catch(IOException e){p.getLogger().warning("orders.yml: "+e.getMessage());}}
 private void write(String s,Map<Long,Order>m){for(Order o:m.values()){String x=s+"."+o.id();d.set(x+".buyer",o.buyer().toString());d.set(x+".buyer-name",o.buyerName());d.set(x+".item",o.item());d.set(x+".remaining",o.remaining());d.set(x+".total",o.totalPrice());d.set(x+".per",o.pricePerItem());d.set(x+".expires",o.expiresAt());d.set(x+".status",o.status());}}
 private boolean blocked(ItemStack i){return i==null||i.getType().isAir()||p.getConfig().getStringList("order.blocked-materials").stream().anyMatch(x->x.equalsIgnoreCase(i.getType().name()));}
 public synchronized Order create(Player b,ItemStack sample,int amount,double total,long exp){Economy e=eco();if(e==null||blocked(sample)||amount<=0||total<=0||exp<=System.currentTimeMillis()||amount>p.getConfig().getInt("order.max-amount",2304)||total>p.getConfig().getDouble("order.max-price",1e9)||!e.has(b,total))return null;if(!e.withdrawPlayer(b,total).transactionSuccess())return null;Order o=new Order(next++,b.getUniqueId(),b.getName(),sample.clone(),amount,total,total/amount,exp,"ACTIVE");a.put(o.id(),o);save();return o;}
 public synchronized Order get(long id){expire();return a.get(id);}public synchronized List<Order> active(){expire();return new ArrayList<>(a.values());}
 public synchronized List<Order> byBuyer(UUID u,boolean all){expire();List<Order>r=new ArrayList<>();for(Order o:a.values())if(o.buyer().equals(u))r.add(o);if(all)for(Order o:h.values())if(o.buyer().equals(u))r.add(o);r.sort(Comparator.comparingLong(Order::id).reversed());return r;}
 public synchronized List<Order> search(String s){expire();List<Order>r=new ArrayList<>();for(Order o:a.values())if(o.item().getType().name().equalsIgnoreCase(s))r.add(o);return r;}
 public synchronized boolean cancel(Player b,long id){Order o=a.get(id);if(o==null||!o.buyer().equals(b.getUniqueId()))return false;a.remove(id);refund(o.buyer(),o.paymentFor(o.remaining()));h.put(id,new Order(o.id(),o.buyer(),o.buyerName(),o.item(),o.remaining(),o.totalPrice(),o.pricePerItem(),o.expiresAt(),"CANCELLED"));save();return true;}
 public synchronized boolean fulfill(Player s,long id,ItemStack supplied){Order o=a.get(id);Economy e=eco();Player b=o==null?null:Bukkit.getPlayer(o.buyer());if(o==null||o.expired()||o.buyer().equals(s.getUniqueId())||b==null||!b.isOnline()||supplied==null||!supplied.isSimilar(o.item()))return false;int n=Math.min(supplied.getAmount(),o.remaining());if(n<=0)return false;ItemStack give=supplied.clone();give.setAmount(n);if(!b.getInventory().addItem(give).isEmpty())return false;double pay=o.paymentFor(n);if(!e.depositPlayer(Bukkit.getOfflinePlayer(s.getUniqueId()),pay).transactionSuccess()){remove(b,give);return false;}int left=o.remaining()-n;a.remove(id);if(left>0)a.put(id,new Order(o.id(),o.buyer(),o.buyerName(),o.item(),left,o.totalPrice(),o.pricePerItem(),o.expiresAt(),"ACTIVE"));else h.put(id,new Order(o.id(),o.buyer(),o.buyerName(),o.item(),0,o.totalPrice(),o.pricePerItem(),o.expiresAt(),"COMPLETED"));save();b.sendMessage(ChatColor.GREEN+"☀ Your order #"+id+" was "+(left>0?"partially ":"")+"fulfilled! "+n+" supplied. Remaining: "+left+".");s.sendMessage(ChatColor.GREEN+"☀ You received $"+money(pay)+" for order #"+id+".");return true;}
 private void remove(Player b,ItemStack x){for(int i=0;i<b.getInventory().getSize();i++){ItemStack z=b.getInventory().getItem(i);if(z!=null&&z.isSimilar(x)){z.setAmount(z.getAmount()-x.getAmount());return;}}}
 private void refund(UUID u,double x){if(x>0&&eco()!=null)eco().depositPlayer(Bukkit.getOfflinePlayer(u),x);}
 private void expire(){boolean c=false;Iterator<Order>it=a.values().iterator();while(it.hasNext()){Order o=it.next();if(!o.expired())continue;it.remove();refund(o.buyer(),o.paymentFor(o.remaining()));h.put(o.id(),new Order(o.id(),o.buyer(),o.buyerName(),o.item(),o.remaining(),o.totalPrice(),o.pricePerItem(),o.expiresAt(),"EXPIRED"));Player b=Bukkit.getPlayer(o.buyer());if(b!=null)b.sendMessage(ChatColor.RED+"☀ Order #"+o.id()+" expired. Remaining escrow was refunded.");c=true;}if(c)save();}
 public String money(double x){return String.format(Locale.US,"%.2f",x);}
}