package net.sunlightsmp.playersettings;
import org.bukkit.*;import org.bukkit.block.Block;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.block.BlockBreakEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.PersistentDataType;import java.util.*;
public final class SunlightTreeChopper implements Listener{
 private final NamespacedKey marker,expiry;public SunlightTreeChopper(SunlightPlayerSettings p){marker=new NamespacedKey(p,"sunlight_tree_chopper");expiry=new NamespacedKey(p,"sunlight_tree_chopper_expiry");}
 public ItemStack create(){ItemStack i=new ItemStack(Material.NETHERITE_AXE);ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.GOLD+"☀ Sunlight Tree Chopper");m.setLore(List.of(ChatColor.GRAY+"Breaks connected trees instantly.",ChatColor.GREEN+"TREE CHOPPER",ChatColor.RED+"Expires in 2 days",ChatColor.DARK_GRAY+"Temporary Sunlight tool"));m.setUnbreakable(true);m.getPersistentDataContainer().set(marker,PersistentDataType.BYTE,(byte)1);m.getPersistentDataContainer().set(expiry,PersistentDataType.LONG,System.currentTimeMillis()+2L*24*60*60*1000);i.setItemMeta(m);return i;}
 private boolean isTool(ItemStack i){if(i==null||i.getType()!=Material.NETHERITE_AXE||!i.hasItemMeta())return false;Byte b=i.getItemMeta().getPersistentDataContainer().get(marker,PersistentDataType.BYTE);return b!=null&&b==1;}
 private boolean expired(ItemStack i){Long t=i.getItemMeta().getPersistentDataContainer().get(expiry,PersistentDataType.LONG);return t==null||System.currentTimeMillis()>=t;}
 private boolean log(Material m){String n=m.name();return n.endsWith("_LOG")||n.endsWith("_STEM")||n.endsWith("_WOOD")||n.endsWith("_HYPHAE")||n.equals("BAMBOO_BLOCK");}
 @EventHandler(priority=EventPriority.HIGH,ignoreCancelled=true) public void onBreak(BlockBreakEvent e){Player p=e.getPlayer();ItemStack tool=p.getInventory().getItemInMainHand();if(!isTool(tool))return;if(expired(tool)){e.setCancelled(true);p.getInventory().setItemInMainHand(null);p.sendMessage(ChatColor.RED+"☀ Your Sunlight Tree Chopper has expired.");return;}Block start=e.getBlock();if(!log(start.getType()))return;Set<Block> found=new LinkedHashSet<>();ArrayDeque<Block> q=new ArrayDeque<>();q.add(start);while(!q.isEmpty()&&found.size()<256){Block b=q.poll();if(!found.add(b)||!log(b.getType()))continue;for(int dx=-1;dx<=1;dx++)for(int dy=-1;dy<=1;dy++)for(int dz=-1;dz<=1;dz++)if(Math.abs(dx)+Math.abs(dy)+Math.abs(dz)==1){Block n=b.getRelative(dx,dy,dz);if(!found.contains(n)&&log(n.getType()))q.add(n);}}if(found.size()<=1)return;e.setCancelled(true);for(Block b:found)b.breakNaturally(tool);p.sendMessage(ChatColor.GREEN+"☀ Tree chopped! "+ChatColor.YELLOW+found.size()+" logs");}
}