package net.sunlightsmp.playersettings;

import org.bukkit.*;import org.bukkit.block.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.block.*;import org.bukkit.event.player.*;import org.bukkit.event.inventory.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.*;import org.bukkit.persistence.PersistentDataType;import org.bukkit.scheduler.BukkitRunnable;import org.bukkit.configuration.file.*;import java.io.*;import java.util.*;

public final class SunlightSpawnerManager implements Listener{
 private final SunlightPlayerSettings plugin; private final NamespacedKey marker; private final File file; private FileConfiguration data; private final Set<Location> active=new HashSet<>(); private final Map<UUID,Location> menus=new HashMap<>();
 public SunlightSpawnerManager(SunlightPlayerSettings p){plugin=p;marker=new NamespacedKey(p,"sunlight_spawner");file=new File(p.getDataFolder(),"spawners.yml");data=YamlConfiguration.loadConfiguration(file);scanLoadedChunks();new BukkitRunnable(){public void run(){scanLoadedChunks();tick();}}.runTaskTimer(plugin,100L,500L);}
 private String key(Location l){return l.getWorld().getUID()+":"+l.getBlockX()+":"+l.getBlockY()+":"+l.getBlockZ();}
 private void scanLoadedChunks(){for(World w:Bukkit.getWorlds())for(Chunk c:w.getLoadedChunks())scanChunk(c);}
 private void scanChunk(Chunk c){for(int x=0;x<16;x++)for(int z=0;z<16;z++)for(int y=c.getWorld().getMinHeight();y<c.getWorld().getMaxHeight();y++){Block b=c.getBlock(c.getX()*16+x,y,c.getZ()*16+z);if(b.getType()!=Material.SPAWNER)continue;CreatureSpawner s=(CreatureSpawner)b.getState();if(s.getPersistentDataContainer().get(marker,PersistentDataType.STRING)!=null&&dropFor(s.getSpawnedType())!=null){active.add(b.getLocation());if(!data.contains(key(b.getLocation())))data.set(key(b.getLocation()),0);}}}
 @EventHandler public void chunkLoad(ChunkLoadEvent e){scanChunk(e.getChunk());}
 @EventHandler public void place(BlockPlaceEvent e){if(e.getBlockPlaced().getType()!=Material.SPAWNER)return;CreatureSpawner s=(CreatureSpawner)e.getBlockPlaced().getState();EntityType t=s.getSpawnedType();if(t==null||dropFor(t)==null)return;s.getPersistentDataContainer().set(marker,PersistentDataType.STRING,t.name());s.update(true,false);active.add(e.getBlockPlaced().getLocation());data.set(key(e.getBlockPlaced().getLocation()),0);save();}
 @EventHandler public void breakBlock(BlockBreakEvent e){if(e.getBlock().getType()!=Material.SPAWNER)return;Location l=e.getBlock().getLocation();CreatureSpawner s=(CreatureSpawner)e.getBlock().getState();if(s.getPersistentDataContainer().get(marker,PersistentDataType.STRING)!=null){int stored=data.getInt(key(l),0);if(stored>0)e.getBlock().getWorld().dropItemNaturally(l.clone().add(.5,1,.5),new ItemStack(dropFor(s.getSpawnedType()),stored));data.set(key(l),null);save();}active.remove(l);}
 private void tick(){boolean changed=false;Iterator<Location> it=active.iterator();while(it.hasNext()){Location l=it.next();if(l.getWorld()==null||!l.getChunk().isLoaded()||l.getBlock().getType()!=Material.SPAWNER){it.remove();continue;}CreatureSpawner s=(CreatureSpawner)l.getBlock().getState();String mark=s.getPersistentDataContainer().get(marker,PersistentDataType.STRING);EntityType t=s.getSpawnedType();if(mark==null||t==null||dropFor(t)==null){it.remove();continue;}int amount=data.getInt(key(l),0);data.set(key(l),amount+amountPerCycle(t));changed=true;}if(changed)save();}
 private int amountPerCycle(EntityType t){return switch(t){case SKELETON->8;case ZOMBIE->8;case WITCH->8;case IRON_GOLEM->8;case SPIDER->8;case CREEPER->8;default->0;};}
 private Material dropFor(EntityType t){return switch(t){case SKELETON->Material.BONE;case ZOMBIE->Material.ROTTEN_FLESH;case WITCH->Material.GLOWSTONE_DUST;case IRON_GOLEM->Material.IRON_INGOT;case SPIDER->Material.STRING;case CREEPER->Material.GUNPOWDER;default->null;};}
 private void save(){try{data.save(file);}catch(IOException ex){plugin.getLogger().warning("Could not save spawners.yml: "+ex.getMessage());}}
 private ItemStack item(Material m,String name,String lore){ItemStack x=new ItemStack(m);ItemMeta im=x.getItemMeta();im.setDisplayName(name);im.setLore(List.of(lore));x.setItemMeta(im);return x;}
 @EventHandler public void rightClick(PlayerInteractEvent e){if(e.getAction()!=Action.RIGHT_CLICK_BLOCK||e.getClickedBlock()==null||e.getClickedBlock().getType()!=Material.SPAWNER)return;CreatureSpawner s=(CreatureSpawner)e.getClickedBlock().getState();if(s.getPersistentDataContainer().get(marker,PersistentDataType.STRING)==null)return;e.setCancelled(true);Player p=e.getPlayer();Location l=e.getClickedBlock().getLocation();String title=ChatColor.GOLD+"☀ "+pretty(s.getSpawnedType())+" Spawner";Inventory inv=plugin.getServer().createInventory(null,27,title);fill(inv,Material.BLACK_STAINED_GLASS_PANE);int stored=data.getInt(key(l),0);Material drop=dropFor(s.getSpawnedType());inv.setItem(13,item(drop,ChatColor.YELLOW+"☀ Stored "+pretty(drop.name()),ChatColor.GRAY+"Amount: "+ChatColor.WHITE+stored));inv.setItem(15,item(Material.CHEST,ChatColor.GOLD+"COLLECT",ChatColor.GRAY+"Take all stored drops"));inv.setItem(11,item(Material.HOPPER,ChatColor.YELLOW+"☀ "+stored+" Stored",ChatColor.GRAY+"Generated: 8 every 25 seconds"));menus.put(p.getUniqueId(),l);p.openInventory(inv);}
 private void fill(Inventory i,Material m){ItemStack x=item(m," ", "");for(int n=0;n<i.getSize();n++)i.setItem(n,x.clone());}
 @EventHandler public void click(InventoryClickEvent e){Location l=menus.get(e.getWhoClicked().getUniqueId());if(l==null)return;e.setCancelled(true);if(e.getRawSlot()!=15)return;String k=key(l);int stored=data.getInt(k,0);if(stored<=0){e.getWhoClicked().sendMessage(ChatColor.RED+"☀ This spawner has nothing stored.");return;}if(!(e.getWhoClicked() instanceof Player p))return;Material drop=dropFor(((CreatureSpawner)l.getBlock().getState()).getSpawnedType());ItemStack x=new ItemStack(drop,stored);Map<Integer,ItemStack> left=p.getInventory().addItem(x);left.values().forEach(v->p.getWorld().dropItemNaturally(p.getLocation(),v));int given=stored;int remaining=left.values().stream().mapToInt(ItemStack::getAmount).sum();data.set(k,remaining);save();p.sendMessage(ChatColor.GREEN+"☀ Collected "+(given-remaining)+" "+pretty(drop.name())+" from the spawner.");p.closeInventory();}
 @EventHandler public void close(InventoryCloseEvent e){menus.remove(e.getPlayer().getUniqueId());}
 private String pretty(EntityType t){String s=t.name().toLowerCase(Locale.ROOT).replace('_',' ');return Character.toUpperCase(s.charAt(0))+s.substring(1);}
 private String pretty(String s){s=s.toLowerCase(Locale.ROOT).replace('_',' ');return Character.toUpperCase(s.charAt(0))+s.substring(1);}
}