package net.sunlightsmp.playersettings;

import org.bukkit.*;import org.bukkit.block.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.block.*;import org.bukkit.event.inventory.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.*;import org.bukkit.persistence.PersistentDataType;import org.bukkit.configuration.file.*;import java.io.*;import java.util.*;

public final class SunlightCrateManager implements Listener{
 private static final String MENU="☀ Sunlight Crates";private final SunlightPlayerSettings plugin;private final Random random=new Random();private final Map<UUID,String> editing=new HashMap<>(),previewing=new HashMap<>(),picking=new HashMap<>();private File file;private FileConfiguration cfg;private final String[] types={"common","spawner","sunlight","crimson","sunset"};private final Material[] icons={Material.WHITE_SHULKER_BOX,Material.YELLOW_SHULKER_BOX,Material.LIME_SHULKER_BOX,Material.RED_SHULKER_BOX,Material.PURPLE_SHULKER_BOX};private final ChatColor[] colors={ChatColor.GREEN,ChatColor.YELLOW,ChatColor.GOLD,ChatColor.RED,ChatColor.LIGHT_PURPLE};private final NamespacedKey crateKey, keyKey, sunsetElytraKey;
 public SunlightCrateManager(SunlightPlayerSettings p){plugin=p;crateKey=new NamespacedKey(p,"sunlight_crate_type");keyKey=new NamespacedKey(p,"sunlight_crate_key_type");sunsetElytraKey=new NamespacedKey(p,"sunset_elytra");reload();}public void reload(){file=new File(plugin.getDataFolder(),"crates.yml");if(!file.exists())plugin.saveResource("crates.yml",false);cfg=YamlConfiguration.loadConfiguration(file);}private void save(){try{cfg.save(file);}catch(IOException e){plugin.getLogger().warning("Could not save crates.yml: "+e.getMessage());}}
 private String norm(String s){return s.toLowerCase(Locale.ROOT).replace("_","");}private boolean valid(String s){return Arrays.asList(types).contains(s);}private String pretty(String s){return Character.toUpperCase(s.charAt(0))+s.substring(1);}private int index(String t){for(int i=0;i<types.length;i++)if(types[i].equals(t))return i;return 0;}private ChatColor color(String t){return colors[index(t)];}private ItemStack item(Material m,String n,List<String> l){ItemStack x=new ItemStack(m);ItemMeta z=x.getItemMeta();z.setDisplayName(n);z.setLore(l);x.setItemMeta(z);return x;}private void fill(Inventory i,Material m){for(int n=0;n<i.getSize();n++)i.setItem(n,item(m," ",List.of()));}
 public ItemStack createCrate(String raw){String t=norm(raw);if(!valid(t))return null;ItemStack x=new ItemStack(icons[index(t)]);ItemMeta z=x.getItemMeta();z.setDisplayName(color(t)+"☀ "+pretty(t)+" Crate");z.setLore(List.of(ChatColor.GRAY+"Right-click to open",ChatColor.YELLOW+"Place this crate in the world"));z.getPersistentDataContainer().set(crateKey,PersistentDataType.STRING,t);x.setItemMeta(z);return x;}
 public void giveCrate(Player p,String raw,int amount){String t=norm(raw);if(!valid(t)){p.sendMessage(ChatColor.RED+"☀ Unknown crate.");return;}amount=Math.max(1,Math.min(64,amount));ItemStack x=createCrate(t);x.setAmount(amount);p.getInventory().addItem(x).values().forEach(v->p.getWorld().dropItemNaturally(p.getLocation(),v));p.sendMessage(ChatColor.GREEN+"☀ Given "+amount+" "+color(t)+pretty(t)+" Crate(s).");}
 public void placeCrate(Player p,String raw){String t=norm(raw);if(!valid(t)){p.sendMessage(ChatColor.RED+"☀ Unknown crate.");return;}Block target=p.getTargetBlockExact(6);if(target==null){p.sendMessage(ChatColor.RED+"☀ Look at a block within 6 blocks.");return;}Block place=target.getRelative(BlockFace.UP);if(!place.getType().isAir()){p.sendMessage(ChatColor.RED+"☀ There is no room above that block.");return;}place.setType(icons[index(t)],false);if(place.getState() instanceof TileState state){state.getPersistentDataContainer().set(crateKey,PersistentDataType.STRING,t);state.update(true,false);}p.sendMessage(ChatColor.GREEN+"☀ Placed "+color(t)+pretty(t)+" Crate.");}
 public void openMenu(Player p){Inventory i=plugin.getServer().createInventory(null,54,MENU);fill(i,Material.BLACK_STAINED_GLASS_PANE);for(int n=0;n<5;n++){int slot=10+n*7;i.setItem(slot,item(icons[n],color(types[n])+"☀ "+pretty(types[n])+" Crate",List.of(ChatColor.GRAY+"View rewards",ChatColor.DARK_GRAY+"Right-click a placed crate to open",ChatColor.YELLOW+"Click to view")));}for(int s:new int[]{0,1,2,3,4,5,6,7,8,45,46,47,48,50,51,52,53})i.setItem(s,item(Material.YELLOW_STAINED_GLASS_PANE,ChatColor.GOLD+"☀",List.of()));i.setItem(49,item(Material.SUNFLOWER,ChatColor.YELLOW+"☀ SUNLIGHT CRATES ☀",List.of(ChatColor.GRAY+"5 custom crates")));p.openInventory(i);}
 public void openPreview(Player p,String raw){String t=norm(raw);if(!valid(t)){p.sendMessage(ChatColor.RED+"☀ Unknown crate.");return;}List<ItemStack> r=rewards(t);String title=color(t)+"☀ "+pretty(t)+" Crate Rewards";Inventory i=plugin.getServer().createInventory(null,54,title);fill(i,Material.BLACK_STAINED_GLASS_PANE);for(int n=0;n<Math.min(28,r.size());n++)i.setItem(10+(n/7)*9+n%7,r.get(n).clone());i.setItem(49,item(icons[index(t)],ChatColor.GREEN+"☀ OPEN CRATE",List.of(ChatColor.GRAY+"Requires a "+pretty(t)+" Crate",ChatColor.YELLOW+"Click to roll")));i.setItem(53,item(Material.BARRIER,ChatColor.RED+"CLOSE",List.of()));previewing.put(p.getUniqueId(),t);p.openInventory(i);}
 public void openCrate(Player p,String raw){String t=norm(raw);if(!valid(t))return;if(!takeKeyOrCrate(p,t)){p.sendMessage(ChatColor.RED+"☀ You need a "+pretty(t)+" Crate Key or Crate.");return;}List<ItemStack> r=rewards(t);if(r.isEmpty()){p.sendMessage(ChatColor.RED+"☀ This crate has no rewards.");return;}if(!t.equals("common")){openPickReward(p,t,r);return;}String title=color(t)+"☀ "+pretty(t)+" Crate";Inventory i=plugin.getServer().createInventory(null,54,title);fill(i,Material.BLACK_STAINED_GLASS_PANE);for(int n=0;n<7;n++)i.setItem(10+n*5,r.get(n%r.size()).clone());i.setItem(22,item(icons[index(t)],color(t)+"☀ "+pretty(t)+" Crate",List.of(color(t)+"ROLLING...")));p.openInventory(i);for(int f=0;f<24;f++){final int q=f;plugin.getServer().getScheduler().runTaskLater(plugin,()->{if(!p.isOnline()||!p.getOpenInventory().getTitle().equals(title))return;for(int n=0;n<7;n++)i.setItem(10+n*5,r.get(random.nextInt(r.size())).clone());p.sendActionBar(color(t)+"☀ COMMON KEY  •  ROLLING "+(q+1)+"/24");p.playSound(p.getLocation(),Sound.BLOCK_NOTE_BLOCK_PLING,.8f,.7f+q*.06f);},q*5L);}plugin.getServer().getScheduler().runTaskLater(plugin,()->{if(!p.isOnline()||!p.getOpenInventory().getTitle().equals(title))return;ItemStack win=r.get(random.nextInt(r.size())).clone();giveReward(p,win);p.closeInventory();p.sendMessage(color(t)+"☀ CRATE OPENED! "+ChatColor.GRAY+"You won "+ChatColor.WHITE+name(win)+" x"+win.getAmount()+"!");p.playSound(p.getLocation(),Sound.ENTITY_PLAYER_LEVELUP,1f,1.4f);},125L);}
 private void openPickReward(Player p,String t,List<ItemStack> rewards){String title=color(t)+"☀ "+pretty(t)+" Crate • Pick a Reward";Inventory i=plugin.getServer().createInventory(null,54,title);fill(i,Material.BLACK_STAINED_GLASS_PANE);for(int n=0;n<Math.min(28,rewards.size());n++)i.setItem(10+(n/7)*9+n%7,rewards.get(n).clone());i.setItem(49,item(icons[index(t)],color(t)+"☀ PICK YOUR REWARD",List.of(ChatColor.GRAY+"Choose one reward")));picking.put(p.getUniqueId(),t);p.openInventory(i);p.sendTitle(color(t)+"☀ "+pretty(t)+" Crate","Pick your reward",5,40,10);}
 private void giveReward(Player p,ItemStack win){Map<Integer,ItemStack> left=p.getInventory().addItem(win.clone());left.values().forEach(x->p.getWorld().dropItemNaturally(p.getLocation(),x));}
 private boolean takeKeyOrCrate(Player p,String t){String keyName=color(t)+"☀ "+pretty(t)+" Crate Key";for(ItemStack x:p.getInventory().getContents())if(x!=null&&x.hasItemMeta()){ItemMeta m=x.getItemMeta();String n=m.getDisplayName();String marked=m.getPersistentDataContainer().get(keyKey,PersistentDataType.STRING);if(x.getType()==Material.TRIPWIRE_HOOK&&t.equals(marked)){x.setAmount(x.getAmount()-1);return true;}if(x.getType()==Material.TRIPWIRE_HOOK&&keyName.equals(n)){x.setAmount(x.getAmount()-1);return true;}if(t.equals(m.getPersistentDataContainer().get(crateKey,PersistentDataType.STRING))){x.setAmount(x.getAmount()-1);return true;}}return false;}
 public void giveKey(Player p,String raw,int a){String t=norm(raw);if(!valid(t)){p.sendMessage(ChatColor.RED+"☀ Unknown crate.");return;}a=Math.max(1,Math.min(64,a));ItemStack k=item(Material.TRIPWIRE_HOOK,color(t)+"☀ "+pretty(t)+" Crate Key",List.of(ChatColor.GRAY+"Use at /suncrates",ChatColor.DARK_GRAY+"Sunlight crate key"));ItemMeta km=k.getItemMeta();km.getPersistentDataContainer().set(keyKey,PersistentDataType.STRING,t);k.setItemMeta(km);k.setAmount(a);p.getInventory().addItem(k).values().forEach(x->p.getWorld().dropItemNaturally(p.getLocation(),x));}
 public void openEditor(Player p,String raw){if(!p.hasPermission("sunlightsmp.crates.admin")){p.sendMessage(ChatColor.RED+"No permission.");return;}String t=norm(raw);if(!valid(t)){p.sendMessage(ChatColor.RED+"☀ Unknown crate.");return;}editing.put(p.getUniqueId(),t);Inventory i=plugin.getServer().createInventory(null,54,ChatColor.DARK_AQUA+"✎ Edit "+pretty(t));fill(i,Material.GRAY_STAINED_GLASS_PANE);List<ItemStack> r=rewards(t);for(int n=0;n<Math.min(28,r.size());n++)i.setItem(10+(n/7)*9+n%7,r.get(n).clone());i.setItem(45,item(icons[index(t)],ChatColor.AQUA+"EDITING",List.of(ChatColor.GRAY+"Put rewards in slots 10-43")));i.setItem(49,item(Material.EMERALD,ChatColor.GREEN+"SAVE CRATE",List.of(ChatColor.GRAY+"Save rewards")));i.setItem(53,item(Material.BARRIER,ChatColor.RED+"CANCEL",List.of(ChatColor.GRAY+"Discard changes")));p.openInventory(i);}
 private void saveEditor(Player p){String t=editing.get(p.getUniqueId());if(t==null)return;Inventory i=p.getOpenInventory().getTopInventory();List<ItemStack> r=new ArrayList<>();for(int row=1;row<=4;row++)for(int col=1;col<=7;col++){ItemStack x=i.getItem(row*9+col);if(x!=null&&!x.getType().isAir()&&!isFiller(x))r.add(x.clone());}if(r.isEmpty()){p.sendMessage(ChatColor.RED+"☀ Add at least one reward.");return;}editing.remove(p.getUniqueId());cfg.set(t+".rewards",r);save();p.closeInventory();p.sendMessage(ChatColor.GREEN+"☀ "+pretty(t)+" rewards saved!");}
 private List<ItemStack> rewards(String t){List<ItemStack> out=new ArrayList<>();List<?> saved=cfg.getList(t+".rewards");if(saved!=null)for(Object o:saved)if(o instanceof ItemStack x&&!isFiller(x))out.add(x.clone());if(!out.isEmpty())return out;for(Map<?,?> m:cfg.getMapList(t)){String ms=String.valueOf(m.get("material")).toUpperCase(Locale.ROOT);int a=parse(String.valueOf(m.get("amount")));try{if(ms.equals("SUNSET_ELYTRA")) out.add(sunsetElytra()); else if(ms.endsWith("_SPAWNER")){EntityType e=EntityType.valueOf(ms.substring(0,ms.length()-8));out.add(spawner(e,a));}else out.add(item(Material.valueOf(ms),ChatColor.WHITE+"",List.of()));out.get(out.size()-1).setAmount(a);}catch(Exception ignored){}}return out;}
 private boolean isFiller(ItemStack x){if(x==null||x.getType().isAir())return true;Material m=x.getType();if(m==Material.BLACK_STAINED_GLASS_PANE||m==Material.GRAY_STAINED_GLASS_PANE||m==Material.YELLOW_STAINED_GLASS_PANE){if(!x.hasItemMeta()||!x.getItemMeta().hasDisplayName())return true;String n=x.getItemMeta().getDisplayName();return n==null||n.trim().isEmpty()||n.equals(" ");}return false;}
 private int parse(String s){try{if(s.contains("-")){String[] a=s.split("-");int lo=Integer.parseInt(a[0]),hi=Integer.parseInt(a[1]);return lo+random.nextInt(Math.max(1,hi-lo+1));}return Math.max(1,Math.min(64,Integer.parseInt(s)));}catch(Exception e){return 1;}}
 private ItemStack sunsetElytra(){ItemStack x=new ItemStack(Material.ELYTRA);ItemMeta m=x.getItemMeta();m.setDisplayName(ChatColor.LIGHT_PURPLE+"☀ Sunset Elytra");m.setLore(List.of(ChatColor.GRAY+"A rare Sunset Crate reward",ChatColor.YELLOW+"☀ Infinite Firework Boosts",ChatColor.DARK_GRAY+"Firework rockets are returned automatically"));m.getPersistentDataContainer().set(sunsetElytraKey,PersistentDataType.BYTE,(byte)1);x.setItemMeta(m);return x;}
 private boolean isSunsetElytra(ItemStack x){return x!=null&&x.getType()==Material.ELYTRA&&x.hasItemMeta()&&x.getItemMeta().getPersistentDataContainer().has(sunsetElytraKey,PersistentDataType.BYTE);}
 private ItemStack spawner(EntityType e,int a){ItemStack x=new ItemStack(Material.SPAWNER,a);BlockStateMeta m=(BlockStateMeta)x.getItemMeta();CreatureSpawner s=(CreatureSpawner)m.getBlockState();s.setSpawnedType(e);m.setBlockState(s);m.setDisplayName(ChatColor.GOLD+"☀ "+pretty(e.getName())+" Spawner");x.setItemMeta(m);return x;}
 private String name(ItemStack x){return x.hasItemMeta()&&x.getItemMeta().hasDisplayName()&&!x.getItemMeta().getDisplayName().isEmpty()?x.getItemMeta().getDisplayName():x.getType().name();}
 @EventHandler public void place(BlockPlaceEvent e){ItemStack x=e.getItemInHand();if(!x.hasItemMeta())return;String t=x.getItemMeta().getPersistentDataContainer().get(crateKey,PersistentDataType.STRING);if(t==null||!valid(t))return;if(e.getBlockPlaced().getState() instanceof TileState state){state.getPersistentDataContainer().set(crateKey,PersistentDataType.STRING,t);state.update(true,false);}}
 @EventHandler(priority=EventPriority.HIGH,ignoreCancelled=true) public void interact(PlayerInteractEvent e){if(e.getAction()!=Action.RIGHT_CLICK_BLOCK||e.getClickedBlock()==null)return;if(!(e.getClickedBlock().getState() instanceof TileState state))return;String t=state.getPersistentDataContainer().get(crateKey,PersistentDataType.STRING);if(t==null||!valid(t))return;e.setCancelled(true);openPreview(e.getPlayer(),t);}
 @EventHandler(priority=EventPriority.HIGH,ignoreCancelled=true) public void breakCrate(BlockBreakEvent e){if(!(e.getBlock().getState() instanceof TileState state))return;String t=state.getPersistentDataContainer().get(crateKey,PersistentDataType.STRING);if(t==null||!valid(t))return;e.setDropItems(false);e.getBlock().setType(Material.AIR,false);ItemStack x=createCrate(t);e.getBlock().getWorld().dropItemNaturally(e.getBlock().getLocation(),x);}
 @EventHandler public void drag(InventoryDragEvent e){
  String t=e.getView().getTitle();
  if(!t.startsWith(ChatColor.DARK_AQUA+"✎ Edit ")) return;
  for(int s:e.getRawSlots()){
    if(s<0||s>=54) continue;
    int row=s/9,col=s%9;
    boolean rewardSlot=row>=1&&row<=4&&col>=1&&col<=7;
    if(!rewardSlot){e.setCancelled(true);return;}
  }
}
 @EventHandler public void click(InventoryClickEvent e){
  String t=e.getView().getTitle();
  if(t.equals(MENU)){
    e.setCancelled(true);
    if(!(e.getWhoClicked() instanceof Player p)||e.getClickedInventory()!=e.getView().getTopInventory())return;
    for(int n=0;n<5;n++)if(e.getRawSlot()==10+n*7){openPreview(p,types[n]);return;}
  }else if(t.contains(" Crate Rewards")){
    e.setCancelled(true);
    if(!(e.getWhoClicked() instanceof Player p))return;
    if(e.getRawSlot()==49){String type=previewing.remove(p.getUniqueId());if(type!=null)openCrate(p,type);}
    else if(e.getRawSlot()==53){previewing.remove(p.getUniqueId());p.closeInventory();}
  }else if(t.startsWith(ChatColor.DARK_AQUA+"✎ Edit ")){
    int s=e.getRawSlot();
    if(s==49){e.setCancelled(true);saveEditor((Player)e.getWhoClicked());return;}
    if(s==53){e.setCancelled(true);editing.remove(e.getWhoClicked().getUniqueId());pClose(e.getWhoClicked());return;}
    if(e.getClick()==ClickType.SHIFT_LEFT||e.getClick()==ClickType.SHIFT_RIGHT){
      if(e.getClickedInventory()!=e.getView().getBottomInventory())e.setCancelled(true);
      else e.setCancelled(true);
      return;
    }
    if(s>=0&&s<54){
      int row=s/9,col=s%9;
      boolean rewardSlot=row>=1&&row<=4&&col>=1&&col<=7;
      if(!rewardSlot)e.setCancelled(true);
    }
  }else if(t.contains(" Crate • Pick a Reward")){e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player p))return;int s=e.getRawSlot();if(s>=10&&s<46&&s%9>=1&&s%9<=7){ItemStack win=e.getCurrentItem();if(win!=null&&!isFiller(win)){String picked=picking.remove(p.getUniqueId());if(picked!=null){p.closeInventory();giveReward(p,win);p.sendMessage(color(picked)+"☀ REWARD CLAIMED! "+ChatColor.GRAY+"You chose "+ChatColor.WHITE+name(win)+" x"+win.getAmount()+"!p.playSound(p.getLocation(),Sound.ENTITY_PLAYER_LEVELUP,1f,1.4f);}}}}else if(t.endsWith(" Crate"))e.setCancelled(true);
}
private void pClose(org.bukkit.inventory.InventoryHolder h){if(h instanceof Player p)p.closeInventory();}
 @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true) public void infiniteSunsetFireworks(PlayerInteractEvent e){if(e.getAction()!=Action.RIGHT_CLICK_AIR&&e.getAction()!=Action.RIGHT_CLICK_BLOCK)return;Player p=e.getPlayer();if(!isSunsetElytra(p.getInventory().getChestplate()))return;if(p.getInventory().getItemInMainHand().getType()!=Material.FIREWORK_ROCKET&&p.getInventory().getItemInOffHand().getType()!=Material.FIREWORK_ROCKET)return;plugin.getServer().getScheduler().runTaskLater(plugin,()->{if(!p.isOnline()||!isSunsetElytra(p.getInventory().getChestplate()))return;ItemStack r=new ItemStack(Material.FIREWORK_ROCKET,1);if(p.getInventory().getItemInMainHand().getType()==Material.FIREWORK_ROCKET||p.getInventory().getItemInOffHand().getType()==Material.FIREWORK_ROCKET){Map<Integer,ItemStack> left=p.getInventory().addItem(r);left.values().forEach(x->p.getWorld().dropItemNaturally(p.getLocation(),x));}},1L);}
 @EventHandler public void close(InventoryCloseEvent e){
  String t=e.getView().getTitle();
  UUID id=e.getPlayer().getUniqueId();
  if(t.contains(" Crate Rewards"))previewing.remove(id);if(t.contains(" Crate • Pick a Reward"))picking.remove(id);
  if(t.startsWith(ChatColor.DARK_AQUA+"✎ Edit ")) editing.remove(id);
}
}