package net.sunlightsmp.playersettings;
import org.bukkit.*; import org.bukkit.block.Block; import org.bukkit.block.Chest; import org.bukkit.entity.Player; import org.bukkit.event.*; import org.bukkit.event.block.BlockBreakEvent; import org.bukkit.inventory.*; import org.bukkit.inventory.meta.ItemMeta; import org.bukkit.persistence.PersistentDataType; import org.bukkit.block.data.BlockData; import java.text.NumberFormat; import java.util.*;
public final class SunlightSellaxe implements Listener {
 private final SunlightPlayerSettings plugin; private final NamespacedKey marker,expiry;
 public SunlightSellaxe(SunlightPlayerSettings p){plugin=p;marker=new NamespacedKey(p,"sunlight_sellaxe");expiry=new NamespacedKey(p,"sunlight_sellaxe_expiry");}
 public ItemStack create(){ItemStack i=new ItemStack(Material.NETHERITE_AXE);ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.GOLD+"☀ Sunlight Sellaxe");m.setLore(List.of(ChatColor.GRAY+"Breaks chests and sells everything inside.",ChatColor.GREEN+"1.5x SELL MULTIPLIER",ChatColor.DARK_GRAY+"Temporary Sunlight tool"));m.setUnbreakable(true);m.getPersistentDataContainer().set(marker,PersistentDataType.BYTE,(byte)1);m.getPersistentDataContainer().set(expiry,PersistentDataType.LONG,System.currentTimeMillis()+2L*24*60*60*1000);i.setItemMeta(m);return i;}
 private boolean isTool(ItemStack i){if(i==null||i.getType()!=Material.NETHERITE_AXE||!i.hasItemMeta())return false;Byte b=i.getItemMeta().getPersistentDataContainer().get(marker,PersistentDataType.BYTE);return b!=null&&b==1;}
 private boolean expired(ItemStack i){Long t=i.getItemMeta().getPersistentDataContainer().get(expiry,PersistentDataType.LONG);return t==null||System.currentTimeMillis()>=t;}
 @EventHandler(priority=EventPriority.HIGH,ignoreCancelled=true) public void onBreak(BlockBreakEvent e){Player p=e.getPlayer();ItemStack tool=p.getInventory().getItemInMainHand();if(!isTool(tool))return;if(expired(tool)){e.setCancelled(true);p.getInventory().setItemInMainHand(null);p.sendMessage(ChatColor.RED+"☀ Your Sunlight Sellaxe has expired.");return;}Block b=e.getBlock();if(!(b.getState() instanceof Chest chest))return;e.setCancelled(true);BlockData oldData=b.getBlockData().clone();double total=0;int count=0;for(ItemStack x:chest.getInventory().getContents()){if(x==null||x.getType().isAir())continue;total+=SellPricing.price(x.getType())*x.getAmount()*1.5;count+=x.getAmount();}chest.getInventory().clear();b.setType(Material.AIR,false);b.setBlockData(oldData,false);var r=plugin.getServer().getServicesManager().getRegistration(net.milkbowl.vault.economy.Economy.class);if(total<=0){p.sendMessage(ChatColor.YELLOW+"☀ The chest was empty and has been restored.");return;}if(r==null||r.getProvider()==null){p.sendMessage(ChatColor.RED+"Economy is unavailable.");return;}r.getProvider().depositPlayer(p,total);p.sendMessage(ChatColor.GREEN+"☀ Sold "+count+" items for "+ChatColor.GOLD+"$"+NumberFormat.getNumberInstance(Locale.US).format(total)+ChatColor.GREEN+" with the 1.5x multiplier! The chest was restored.");p.playSound(p.getLocation(),Sound.ENTITY_PLAYER_LEVELUP,1f,1.2f);}
}