package net.sunlightsmp.playersettings;
import org.bukkit.*;import org.bukkit.block.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.block.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.persistence.PersistentDataType;import org.bukkit.scheduler.BukkitRunnable;import java.util.*;

public final class SunlightSpawnerManager implements Listener{
 private final SunlightPlayerSettings plugin; private final NamespacedKey marker; private final Set<Location> active=new HashSet<>();
 public SunlightSpawnerManager(SunlightPlayerSettings p){plugin=p;marker=new NamespacedKey(p,"sunlight_spawner"); scanLoadedChunks(); new BukkitRunnable(){public void run(){scanLoadedChunks();tick();}}.runTaskTimer(plugin,100L,500L);}
 private void scanLoadedChunks(){for(World w:Bukkit.getWorlds())for(Chunk c:w.getLoadedChunks())scanChunk(c);}
 private void scanChunk(Chunk c){for(int x=0;x<16;x++)for(int z=0;z<16;z++)for(int y=c.getWorld().getMinHeight();y<c.getWorld().getMaxHeight();y++){Block b=c.getBlock(c.getX()*16+x,y,c.getZ()*16+z);if(b.getType()!=Material.SPAWNER)continue;CreatureSpawner s=(CreatureSpawner)b.getState();if(s.getPersistentDataContainer().get(marker,PersistentDataType.STRING)!=null&&dropFor(s.getSpawnedType())!=null)active.add(b.getLocation());}}
 @EventHandler public void chunkLoad(ChunkLoadEvent e){scanChunk(e.getChunk());}
 @EventHandler public void place(BlockPlaceEvent e){if(e.getBlockPlaced().getType()!=Material.SPAWNER)return;CreatureSpawner s=(CreatureSpawner)e.getBlockPlaced().getState();EntityType t=s.getSpawnedType();if(t==null||dropFor(t)==null)return;s.getPersistentDataContainer().set(marker,PersistentDataType.STRING,t.name());s.update(true,false);active.add(e.getBlockPlaced().getLocation());}
 @EventHandler public void breakBlock(BlockBreakEvent e){if(e.getBlock().getType()==Material.SPAWNER)active.remove(e.getBlock().getLocation());}
 private void tick(){Iterator<Location> it=active.iterator();while(it.hasNext()){Location l=it.next();if(l.getWorld()==null||!l.getChunk().isLoaded()||l.getBlock().getType()!=Material.SPAWNER){it.remove();continue;}CreatureSpawner s=(CreatureSpawner)l.getBlock().getState();String mark=s.getPersistentDataContainer().get(marker,PersistentDataType.STRING);EntityType t=s.getSpawnedType();if(mark==null||t==null||dropFor(t)==null){it.remove();continue;}l.getWorld().dropItemNaturally(l.clone().add(.5,1,.5),new ItemStack(dropFor(t),1));l.getWorld().spawn(l.clone().add(.5,1,.5),ExperienceOrb.class,o->o.setExperience(xpFor(t)));}}
 private Material dropFor(EntityType t){return switch(t){case SKELETON->Material.BONE;case ZOMBIE->Material.ROTTEN_FLESH;case WITCH->Material.GLOWSTONE_DUST;case IRON_GOLEM->Material.IRON_INGOT;case SPIDER->Material.STRING;case CREEPER->Material.GUNPOWDER;default->null;};}
 private int xpFor(EntityType t){return switch(t){case SKELETON,ZOMBIE,SPIDER,CREEPER->5;case WITCH->8;case IRON_GOLEM->12;default->0;};}
 @EventHandler public void rightClick(PlayerInteractEvent e){if(e.getAction()!=Action.RIGHT_CLICK_BLOCK||e.getClickedBlock()==null||e.getClickedBlock().getType()!=Material.SPAWNER)return;CreatureSpawner s=(CreatureSpawner)e.getClickedBlock().getState();if(s.getPersistentDataContainer().get(marker,PersistentDataType.STRING)==null)return;e.setCancelled(true);e.getPlayer().sendActionBar(ChatColor.GOLD+"☀ "+pretty(s.getSpawnedType())+" Spawner "+ChatColor.GRAY+"• Drops every 25 seconds");}
 private String pretty(EntityType t){String s=t.name().toLowerCase(Locale.ROOT).replace('_',' ');return Character.toUpperCase(s.charAt(0))+s.substring(1);}
}